# Site settings
title: Space Takos with Samuel!
description: My Twisty Turny Life as a Fourth Grader!
keywords:
author: Samuel Hedgpeth
baseurl: "samuelhedgpeth.github.io"
url: "http://samuelhedgpeth.github.io" 
